### ISSUE TITLE
[3pts] Create a navigation panel (Student B)

### ISSUE THREAD

**Issue by sebalp100** [sebalp100/hotel-bookings-backend#4]
In the navigation panel, the user can see links to: 
   - Motorcycles/doctors/classes/items that you selected as a theme.
   - "Reserve" form.
   - "My reservations".
   - "Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
   - "Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).

![Image](https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/1f742126425031.563550810ebb3.jpg)

**Comment by enoqueJonas** [comment]
Here you will find the [link](https://github.com/sebalp100/hotel-bookings-frontend/pull/6) to the PR.
